package com.sakethh.linkora.ui.bottomSheets.sorting

enum class SortingBtmSheetType {
    PARENT_HOME_SCREEN, COLLECTIONS_SCREEN, HISTORY_SCREEN,
    REGULAR_FOLDER_SCREEN, ARCHIVE_FOLDER_SCREEN, PARENT_ARCHIVE_SCREEN,
    SAVED_LINKS_SCREEN, IMPORTANT_LINKS_SCREEN, ALL_LINKS_SCREEN
}