package com.sakethh.linkora.ui.navigation

enum class NavigationRoutes {
    HOME_SCREEN, SETTINGS_SCREEN, COLLECTIONS_SCREEN, SPECIFIC_COLLECTION_SCREEN, ARCHIVE_SCREEN, SEARCH_SCREEN,
    ABOUT_SETTINGS_SCREEN, ACKNOWLEDGMENTS_SETTINGS_SCREEN, DATA_SETTINGS_SCREEN, GENERAL_SETTINGS_SCREEN,
    LANGUAGE_SETTINGS_SCREEN, PRIVACY_SETTINGS_SCREEN, THEME_SETTINGS_SCREEN, SHELF_SCREEN, SPECIFIC_PANEL_SCREEN,
    LINK_LAYOUT_SETTINGS, ALL_LINKS_SCREEN
}