package com.sakethh.linkora.ui.screens.settings

enum class SettingsPreferences {
    DYNAMIC_THEMING, JSOUP_USER_AGENT, SECONDARY_JSOUP_USER_AGENT, DARK_THEME, FOLLOW_SYSTEM_THEME, SETTING_COMPONENT_DESCRIPTION_STATE,
    CUSTOM_TABS, AUTO_DETECT_TITLE_FOR_LINK, AUTO_CHECK_UPDATES, HOME_SCREEN_VISIBILITY, SORTING_PREFERENCE,
    SEND_CRASH_REPORTS, IS_DATA_MIGRATION_COMPLETED_FROM_V9, SAVED_APP_CODE, CURRENT_WORK_MANAGER_WORK_UUID,
    REFRESH_LINKS_TABLE_INDEX, REFRESH_IMP_LINKS_TABLE_INDEX, REFRESH_ARCHIVE_LINKS_TABLE_INDEX,
    REFRESH_RECENTLY_VISITED_LINKS_TABLE_INDEX, SHELF_VISIBLE_STATE, LAST_SELECTED_PANEL_ID, APP_LANGUAGE_NAME,
    APP_LANGUAGE_CODE, USE_REMOTE_LANGUAGE_STRINGS, TOTAL_REMOTE_STRINGS, REMOTE_STRINGS_LAST_UPDATED_ON, LOCALIZATION_SERVER_URL,
    ASSOCIATED_IMAGES_IN_LINK_MENU_VISIBILITY, CURRENTLY_SELECTED_LINK_VIEW, BORDER_VISIBILITY_FOR_NON_LIST_VIEWS,
    TITLE_VISIBILITY_FOR_NON_LIST_VIEWS, BASE_URL_VISIBILITY_FOR_NON_LIST_VIEWS, FADED_EDGE_VISIBILITY_FOR_NON_LIST_VIEWS,
    AMOLED_THEME_STATE, FORCE_SAVE_WITHOUT_FETCHING_META_DATA, INITIAL_ROUTE
}